feat: generate struct without json tag
cloudwego/thriftgo pull request #51
Opened 2022-08-05 10:27 UTC by FGYFFFF

#### What type of PR is this?

feat
#### What this PR does / why we need it (en: English/zh: Chinese):

en: Generated struct without "json" tag
zh: 生成的结构体不带 "json" tag

#### Which issue(s) this PR fixes:

2022-08-10 03:05 UTC, simon0-o requested changes

2022-08-10 03:05 UTC, simon0-o commented on generator/golang/option.go
> +	NoJsonTag          bool `no_json_tag:"Generate struct without 'json' tag"`
尽量别用反义参数，可以用比如 'gen_json_tag'，然后默认值设置为 true

2022-08-11 02:32 UTC, FGYFFFF commented on generator/golang/option.go
> +	NoJsonTag          bool `no_json_tag:"Generate struct without 'json' tag"`
我的想法是：thriftgo已经是默认生成 json tag 了，用这个反义参数反而好理解些。另外，少杰那天说让加的这个option， @lsjbd

2022-08-11 03:39 UTC, lsjbd commented on generator/golang/option.go
> +	NoJsonTag          bool `no_json_tag:"Generate struct without 'json' tag"`
赞同 @simon0-o 的说法，反义的参数并不好理解，实践经验来看更容易造成各种误解。

2022-08-16 08:37 UTC, FGYFFFF commented
@lsjbd @simon0-o 再看下呗

2022-08-16 08:38 UTC, simon0-o approved these changes

2022-08-16 09:18 UTC, lsjbd approved these changes

2022-08-16 09:18 UTC, merged